/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiVersion {
  version?: string;
}

export const apiVersionSchema: Schema<ApiVersion> = object({
  version: ['version', optional(string())],
});
