/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Classification, classificationSchema } from './classification';
import { Meta, metaSchema } from './meta';

export interface ClassifyResponse {
  id: string;
  classifications: Classification[];
  meta?: Meta;
}

export const classifyResponseSchema: Schema<ClassifyResponse> = object({
  id: ['id', string()],
  classifications: ['classifications', array(lazy(() => classificationSchema))],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
