/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface DetectLanguageRequest {
  /** List of strings to run the detection on. */
  texts: string[];
}

export const detectLanguageRequestSchema: Schema<DetectLanguageRequest> = object(
  { texts: ['texts', array(string())] }
);
