/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Meta, metaSchema } from './meta';

export interface DetokenizeResponse {
  /** A string representing the list of tokens. */
  text: string;
  meta?: Meta;
}

export const detokenizeResponseSchema: Schema<DetokenizeResponse> = object({
  text: ['text', string()],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
