/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface DetokenizeRequest {
  /** The list of tokens to be detokenized. */
  tokens: number[];
  /** An optional parameter to provide the model name. This will ensure that the detokenization is done by the tokenizer used by that model. */
  model?: string;
}

export const detokenizeRequestSchema: Schema<DetokenizeRequest> = object({
  tokens: ['tokens', array(number())],
  model: ['model', optional(string())],
});
