/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** The doc object which was ranked */
export interface Document1 {
  /** The text of the document to rerank */
  text: string;
}

export const document1Schema: Schema<Document1> = object({
  text: ['text', string()],
});
