/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Document2 {
  /** The text of the document to rerank */
  text: string;
}

export const document2Schema: Schema<Document2> = object({
  text: ['text', string()],
});
