/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExtractivenessEnum
 */
export enum ExtractivenessEnum {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
}

/**
 * Schema for ExtractivenessEnum
 */
export const extractivenessEnumSchema: Schema<ExtractivenessEnum> = stringEnum(ExtractivenessEnum);
