/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FinishReasonEnum
 */
export enum FinishReasonEnum {
  COMPLETE = 'COMPLETE',
  ERROR = 'ERROR',
  ERRORTOXIC = 'ERROR_TOXIC',
  ERRORLIMIT = 'ERROR_LIMIT',
  USERCANCEL = 'USER_CANCEL',
  MAXTOKENS = 'MAX_TOKENS',
}

/**
 * Schema for FinishReasonEnum
 */
export const finishReasonEnumSchema: Schema<FinishReasonEnum> = stringEnum(FinishReasonEnum);
