/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FormatEnum
 */
export enum FormatEnum {
  Paragraph = 'paragraph',
  Bullets = 'bullets',
}

/**
 * Schema for FormatEnum
 */
export const formatEnumSchema: Schema<FormatEnum> = stringEnum(FormatEnum);
