/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Meta, metaSchema } from './meta';
import { SingleGeneration, singleGenerationSchema } from './singleGeneration';

export interface Generation {
  id: string;
  /** Prompt used for generations. */
  prompt?: string;
  /** List of generated results */
  generations: SingleGeneration[];
  meta?: Meta;
}

export const generationSchema: Schema<Generation> = object({
  id: ['id', string()],
  prompt: ['prompt', optional(string())],
  generations: ['generations', array(lazy(() => singleGenerationSchema))],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
