/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';

export interface GenerationStream {
  /** A segment of text of the generation. */
  text: string;
  /** Refers to the nth generation. Only present when `num_generations` is greater than zero. */
  index?: number;
  isFinished: boolean;
}

export const generationStreamSchema: Schema<GenerationStream> = object({
  text: ['text', string()],
  index: ['index', optional(number())],
  isFinished: ['is_finished', boolean()],
});
