/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface Labels {
  confidence?: number;
}

export const labelsSchema: Schema<Labels> = object({
  confidence: ['confidence', optional(number())],
});
