/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LengthEnum
 */
export enum LengthEnum {
  Short = 'short',
  Medium = 'medium',
  Long = 'long',
}

/**
 * Schema for LengthEnum
 */
export const lengthEnumSchema: Schema<LengthEnum> = stringEnum(LengthEnum);
