/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ApiVersion, apiVersionSchema } from './apiVersion';

export interface Meta {
  apiVersion?: ApiVersion;
}

export const metaSchema: Schema<Meta> = object({
  apiVersion: ['api_version', optional(lazy(() => apiVersionSchema))],
});
