/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Meta, metaSchema } from './meta';
import { Result2, result2Schema } from './result2';

export interface RerankResponse {
  id?: string;
  /** An ordered list of ranked documents */
  results: Result2[];
  meta?: Meta;
}

export const rerankResponseSchema: Schema<RerankResponse> = object({
  id: ['id', optional(string())],
  results: ['results', array(lazy(() => result2Schema))],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
