/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  SingleGenerationInStream,
  singleGenerationInStreamSchema,
} from './singleGenerationInStream';

export interface Response {
  id: string;
  generations?: SingleGenerationInStream;
}

export const responseSchema: Schema<Response> = object({
  id: ['id', string()],
  generations: [
    'generations',
    optional(lazy(() => singleGenerationInStreamSchema)),
  ],
});
