/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Result1 {
  /** Generated ID for the summary */
  id?: string;
  /** Generated summary for the text */
  summary?: string;
}

export const result1Schema: Schema<Result1> = object({
  id: ['id', optional(string())],
  summary: ['summary', optional(string())],
});
