/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReturnLikelihoodsEnum
 */
export enum ReturnLikelihoodsEnum {
  GENERATION = 'GENERATION',
  ALL = 'ALL',
  NONE = 'NONE',
}

/**
 * Schema for ReturnLikelihoodsEnum
 */
export const returnLikelihoodsEnumSchema: Schema<ReturnLikelihoodsEnum> = stringEnum(ReturnLikelihoodsEnum);
