/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { FinishReasonEnum, finishReasonEnumSchema } from './finishReasonEnum';

export interface SingleGenerationInStream {
  id: string;
  /** Full text of the generation. */
  text: string;
  /** Refers to the nth generation. Only present when `num_generations` is greater than zero. */
  index?: number;
  finishReason: FinishReasonEnum;
}

export const singleGenerationInStreamSchema: Schema<SingleGenerationInStream> = object(
  {
    id: ['id', string()],
    text: ['text', string()],
    index: ['index', optional(number())],
    finishReason: ['finish_reason', finishReasonEnumSchema],
  }
);
