/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Meta, metaSchema } from './meta';

export interface SummarizeResponse {
  /** Generated ID for the summary */
  id?: string;
  /** Generated summary for the text */
  summary?: string;
  meta?: Meta;
}

export const summarizeResponseSchema: Schema<SummarizeResponse> = object({
  id: ['id', optional(string())],
  summary: ['summary', optional(string())],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
