/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  ExtractivenessEnum,
  extractivenessEnumSchema,
} from './extractivenessEnum';
import { FormatEnum, formatEnumSchema } from './formatEnum';
import { LengthEnum, lengthEnumSchema } from './lengthEnum';
import { ModelEnum, modelEnumSchema } from './modelEnum';

export interface SummarizeRequest {
  /** The text to generate a summary for. Can be up to 100,000 characters long. Currently the only supported language is English. */
  text: string;
  length?: LengthEnum;
  format?: FormatEnum;
  model?: ModelEnum;
  extractiveness?: ExtractivenessEnum;
  /** Ranges from 0 to 5. Controls the randomness of the output. Lower values tend to generate more “predictable” output, while higher values tend to generate more “creative” output. The sweet spot is typically between 0 and 1. */
  temperature?: number;
  /** A free-form instruction for modifying how the summaries get generated. Should complete the sentence "Generate a summary _". Eg. "focusing on the next steps" or "written by Yoda" */
  additionalCommand?: string;
}

export const summarizeRequestSchema: Schema<SummarizeRequest> = object({
  text: ['text', string()],
  length: ['length', optional(lengthEnumSchema)],
  format: ['format', optional(formatEnumSchema)],
  model: ['model', optional(modelEnumSchema)],
  extractiveness: ['extractiveness', optional(extractivenessEnumSchema)],
  temperature: ['temperature', optional(number())],
  additionalCommand: ['additional_command', optional(string())],
});
