/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Meta, metaSchema } from './meta';

export interface TokenizeResponse {
  /** An array of tokens, where each token is an integer. */
  tokens: number[];
  tokenStrings: string[];
  meta?: Meta;
}

export const tokenizeResponseSchema: Schema<TokenizeResponse> = object({
  tokens: ['tokens', array(number())],
  tokenStrings: ['token_strings', array(string())],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
