/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface TokenLikelihood {
  token: string;
  likelihood: number;
}

export const tokenLikelihoodSchema: Schema<TokenLikelihood> = object({
  token: ['token', string()],
  likelihood: ['likelihood', number()],
});
