/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TokenizeRequest {
  /** The string to be tokenized, the minimum text length is 1 character, and the maximum text length is 65536 characters. */
  text: string;
  /** An optional parameter to provide the model name. This will ensure that the tokenization uses the tokenizer used by that model. */
  model?: string;
}

export const tokenizeRequestSchema: Schema<TokenizeRequest> = object({
  text: ['text', string()],
  model: ['model', optional(string())],
});
