/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TruncateEnum
 */
export enum TruncateEnum {
  NONE = 'NONE',
  START = 'START',
  END = 'END',
}

/**
 * Schema for TruncateEnum
 */
export const truncateEnumSchema: Schema<TruncateEnum> = stringEnum(TruncateEnum);
