/**
 * Cohere APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Result3, result3Schema } from './result3';

export interface V1ClassifyResponse {
  results: Result3[];
}

export const v1ClassifyResponseSchema: Schema<V1ClassifyResponse> = object({
  results: ['results', array(lazy(() => result3Schema))],
});
