/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { Logprobs, logprobsSchema } from './logprobs';

export interface Choice {
  text?: string;
  index?: number;
  logprobs?: Logprobs;
  finishReason?: string;
}

export const choiceSchema: Schema<Choice> = object({
  text: ['text', optional(string())],
  index: ['index', optional(number())],
  logprobs: ['logprobs', optional(lazy(() => logprobsSchema))],
  finishReason: ['finish_reason', optional(string())],
});
