/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Datum, datumSchema } from './datum';

export interface CreateEmbeddingResponse {
  object?: string;
  model?: string;
  data?: Datum[];
}

export const createEmbeddingResponseSchema: Schema<CreateEmbeddingResponse> = object(
  {
    object: ['object', optional(string())],
    model: ['model', optional(string())],
    data: ['data', optional(array(lazy(() => datumSchema)))],
  }
);
