/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Choice, choiceSchema } from './choice';

export interface CreateCompletionResponse {
  id?: string;
  object?: string;
  created?: number;
  model?: string;
  choices?: Choice[];
}

export const createCompletionResponseSchema: Schema<CreateCompletionResponse> = object(
  {
    id: ['id', optional(string())],
    object: ['object', optional(string())],
    created: ['created', optional(number())],
    model: ['model', optional(string())],
    choices: ['choices', optional(array(lazy(() => choiceSchema)))],
  }
);
