/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Choice1, choice1Schema } from './choice1';
import { Usage, usageSchema } from './usage';

export interface CreateChatCompletionResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: Choice1[];
  usage?: Usage;
}

export const createChatCompletionResponseSchema: Schema<CreateChatCompletionResponse> = object(
  {
    id: ['id', string()],
    object: ['object', string()],
    created: ['created', number()],
    model: ['model', string()],
    choices: ['choices', array(lazy(() => choice1Schema))],
    usage: ['usage', optional(lazy(() => usageSchema))],
  }
);
