/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string, unknown } from '../schema';

export interface CreateFileRequest {
  /**
   * Name of the [JSON Lines](https://jsonlines.readthedocs.io/en/latest/) file to be uploaded.
   * If the `purpose` is set to "fine-tune", each line is a JSON record with "prompt" and "completion" fields representing your [training examples](/docs/guides/fine-tuning/prepare-training-data).
   */
  file: NodeJS.ReadableStream | Blob;
  /**
   * The intended purpose of the uploaded documents.
   * Use "fine-tune" for [Fine-tuning](/docs/api-reference/fine-tunes). This allows us to validate the format of the uploaded file.
   */
  purpose: string;
}

export const createFileRequestSchema: Schema<CreateFileRequest> = object({
  file: ['file', unknown()],
  purpose: ['purpose', string()],
});
