/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CreateEmbeddingRequest {
  /** ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them. */
  model: string;
  /**
   * Input text to get embeddings for, encoded as a string or array of tokens. To get embeddings for multiple inputs in a single request, pass an array of strings or array of token arrays. Each input must not exceed 2048 tokens in length.
   * Unless your are embedding code, we suggest replacing newlines (`\n`) in your input with a single space, as we have observed inferior results when newlines are present.
   */
  input: string;
  /** A unique identifier representing your end-user, which will help OpenAI to monitor and detect abuse. */
  user?: string;
}

export const createEmbeddingRequestSchema: Schema<CreateEmbeddingRequest> = object(
  {
    model: ['model', string()],
    input: ['input', string()],
    user: ['user', optional(string())],
  }
);
