/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Datum {
  index?: number;
  object?: string;
  embedding?: number[];
}

export const datumSchema: Schema<Datum> = object({
  index: ['index', optional(number())],
  object: ['object', optional(string())],
  embedding: ['embedding', optional(array(number()))],
});
