/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface DeleteFileResponse {
  id?: string;
  object?: string;
  deleted?: boolean;
}

export const deleteFileResponseSchema: Schema<DeleteFileResponse> = object({
  id: ['id', optional(string())],
  object: ['object', optional(string())],
  deleted: ['deleted', optional(boolean())],
});
