/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

export interface Hyperparameters1 {
  nEpochs?: unknown;
}

export const hyperparameters1Schema: Schema<Hyperparameters1> = object({
  nEpochs: ['n_epochs', optional(unknown())],
});
