/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

/** The hyperparameters used for the fine-tuning job. */
export interface Hyperparameters {
  nEpochs?: unknown;
}

export const hyperparametersSchema: Schema<Hyperparameters> = object({
  nEpochs: ['n_epochs', optional(unknown())],
});
