/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema } from '../schema';
import { Datum2, datum2Schema } from './datum2';

export interface ImagesResponse {
  created: number;
  data: Datum2[];
}

export const imagesResponseSchema: Schema<ImagesResponse> = object({
  created: ['created', number()],
  data: ['data', array(lazy(() => datum2Schema))],
});
