/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { OpenAIFile, openAIFileSchema } from './openAIFile';

export interface ListFilesResponse {
  object?: string;
  data?: OpenAIFile[];
}

export const listFilesResponseSchema: Schema<ListFilesResponse> = object({
  object: ['object', optional(string())],
  data: ['data', optional(array(lazy(() => openAIFileSchema)))],
});
