/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Model, modelSchema } from './model';

export interface ListModelsResponse {
  object?: string;
  data?: Model[];
}

export const listModelsResponseSchema: Schema<ListModelsResponse> = object({
  object: ['object', optional(string())],
  data: ['data', optional(array(lazy(() => modelSchema)))],
});
