/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Logprobs {
  tokens?: string[];
  tokenLogprobs?: number[];
  topLogprobs?: unknown[];
  textOffset?: number[];
}

export const logprobsSchema: Schema<Logprobs> = object({
  tokens: ['tokens', optional(array(string()))],
  tokenLogprobs: ['token_logprobs', optional(array(number()))],
  topLogprobs: ['top_logprobs', optional(array(unknown()))],
  textOffset: ['text_offset', optional(array(number()))],
});
