/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Model {
  id?: string;
  object?: string;
  created?: number;
  ownedBy?: string;
}

export const modelSchema: Schema<Model> = object({
  id: ['id', optional(string())],
  object: ['object', optional(string())],
  created: ['created', optional(number())],
  ownedBy: ['owned_by', optional(string())],
});
