/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface OpenAIFile {
  id?: string;
  object?: string;
  bytes?: number;
  createdAt?: number;
  filename?: string;
  purpose?: string;
  status?: string;
  statusDetails?: unknown | null;
}

export const openAIFileSchema: Schema<OpenAIFile> = object({
  id: ['id', optional(string())],
  object: ['object', optional(string())],
  bytes: ['bytes', optional(number())],
  createdAt: ['created_at', optional(number())],
  filename: ['filename', optional(string())],
  purpose: ['purpose', optional(string())],
  status: ['status', optional(string())],
  statusDetails: ['status_details', optional(nullable(unknown()))],
});
