/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SelectedDocument {
  document?: number;
  text?: string;
}

export const selectedDocumentSchema: Schema<SelectedDocument> = object({
  document: ['document', optional(number())],
  text: ['text', optional(string())],
});
