/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CreateEmbeddingRequest,
  createEmbeddingRequestSchema,
} from '../models/createEmbeddingRequest';
import {
  CreateEmbeddingResponse,
  createEmbeddingResponseSchema,
} from '../models/createEmbeddingResponse';
import { BaseController } from './baseController';

export class EmbeddingsController extends BaseController {
  /**
   * Creates an embedding vector representing the input text.
   *
   * @param body
   * @return Response from the API call
   */
  async createEmbedding(
    body: CreateEmbeddingRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateEmbeddingResponse>> {
    const req = this.createRequest('POST', '/embeddings');
    const mapped = req.prepareArgs({
      body: [body, createEmbeddingRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(createEmbeddingResponseSchema, requestOptions);
  }
}
