/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CreateFineTuneRequest,
  createFineTuneRequestSchema,
} from '../models/createFineTuneRequest';
import { FineTune, fineTuneSchema } from '../models/fineTune';
import { FineTuning, fineTuningSchema } from '../models/fineTuning';
import { string } from '../schema';
import { BaseController } from './baseController';

export class FineTuningController extends BaseController {
  /**
   * Creates a job that fine-tunes a specified model from a given dataset.
   *
   * Response includes details of the enqueued job including job status and the name of the fine-tuned
   * models once complete.
   *
   * [Learn more about Fine-tuning](https://platform.openai.com/docs/guides/fine-tuning)
   *
   * @param body
   * @return Response from the API call
   */
  async createFineTuneJob(
    body: CreateFineTuneRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FineTuning>> {
    const req = this.createRequest('POST', '/fine_tuning/jobs');
    const mapped = req.prepareArgs({
      body: [body, createFineTuneRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(fineTuningSchema, requestOptions);
  }

  /**
   * Immediately cancel a fine-tuning job.
   *
   * @param fineTuningJobId    The ID of the fine-tuning job to cancel
   * @return Response from the API call
   */
  async cancelFineTuning(
    fineTuningJobId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FineTuning>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      fineTuningJobId: [fineTuningJobId, string()],
    });
    req.appendTemplatePath`/fine_tuning/jobs/${mapped.fineTuningJobId}/cancel`;
    return req.callAsJson(fineTuningSchema, requestOptions);
  }

  /**
   * Gets info about the fine-tuning job.
   *
   * [Learn more about Fine-tuning](https://platform.openai.com/docs/guides/fine-tuning)
   *
   * @param fineTuningJobId    The ID of the fine-tuning job
   * @return Response from the API call
   */
  async retrieveFineTuningIob(
    fineTuningJobId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FineTune>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      fineTuningJobId: [fineTuningJobId, string()],
    });
    req.appendTemplatePath`/fine_tuning/jobs/${mapped.fineTuningJobId}`;
    return req.callAsJson(fineTuneSchema, requestOptions);
  }
}
