/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CreateImageRequest,
  createImageRequestSchema,
} from '../models/createImageRequest';
import { ImagesResponse, imagesResponseSchema } from '../models/imagesResponse';
import { BaseController } from './baseController';

export class ImagesController extends BaseController {
  /**
   * Creates an image given a prompt.
   *
   * @param body
   * @return Response from the API call
   */
  async createImage(
    body: CreateImageRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ImagesResponse>> {
    const req = this.createRequest('POST', '/images/generations');
    const mapped = req.prepareArgs({ body: [body, createImageRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(imagesResponseSchema, requestOptions);
  }
}
